# Generated by Django 4.2.3 on 2023-07-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='isAnonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='isAnonymous',
            field=models.BooleanField(default=False),
        ),
    ]
